<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="">

<title>Practical 1 Key - Association Testing</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="QG3_Association_Testing_practical_Key_files/libs/clipboard/clipboard.min.js"></script>
<script src="QG3_Association_Testing_practical_Key_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="QG3_Association_Testing_practical_Key_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="QG3_Association_Testing_practical_Key_files/libs/quarto-html/popper.min.js"></script>
<script src="QG3_Association_Testing_practical_Key_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="QG3_Association_Testing_practical_Key_files/libs/quarto-html/anchor.min.js"></script>
<link href="QG3_Association_Testing_practical_Key_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="QG3_Association_Testing_practical_Key_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="QG3_Association_Testing_practical_Key_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="QG3_Association_Testing_practical_Key_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="QG3_Association_Testing_practical_Key_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Practical 1 Key - Association Testing</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Before you begin:</p>
<ul>
<li>Make sure that R is installed on your computer</li>
<li>For this lab, we will use a few R libraries:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="case-control-association-testing" class="level2">
<h2 class="anchored" data-anchor-id="case-control-association-testing">Case-Control Association Testing</h2>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>We will be using the <a href="https://raw.githubusercontent.com/joellembatchou/SISG2026_Association_Mapping/master/data/LHON.txt">LHON dataset</a> covered in the lecture notes for this portion of the exercises. The LHON dataset is from a case-control study and includes both phenotype and genotype data for a candidate gene.</p>
<p><strong>What we’re testing</strong>: Do individuals with different genotypes have different odds of being a case (having the disease)? We use logistic regression because our outcome is binary (case/control).</p>
<p>Let’s first load the LHON data file into the R session. We need to define the path to the file (if you have it downloaded on your machine, change the path to the file location).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>LHON_FILE <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/joellembatchou/SISG2026_Association_Mapping/master/data/LHON.txt"</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can now read the file</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>LHON <span class="ot">&lt;-</span> <span class="fu">fread</span>(LHON_FILE, <span class="at">header=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="helpful-suggestions-for-r" class="level3">
<h3 class="anchored" data-anchor-id="helpful-suggestions-for-r">Helpful suggestions for R</h3>
<p>There are many ways to obtain summary information for a dataset. Here are some short examples:</p>
<ul>
<li>Get information on number of rows/columns as well as the variables present in the data set</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(LHON)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'data.table' and 'data.frame':  328 obs. of  3 variables:
 $ IID  : chr  "ID1" "ID2" "ID3" "ID4" ...
 $ GENO : chr  "TT" "CT" "TT" "CT" ...
 $ PHENO: chr  "CONTROL" "CONTROL" "CASE" "CONTROL" ...
 - attr(*, ".internal.selfref")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<ul>
<li>Get counts for a specific variable in the table (use <code>$</code> to access a variable)</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(LHON<span class="sc">$</span>GENO)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 CC  CT  TT 
 16  74 238 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cross tabulation for two variables</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(LHON<span class="sc">$</span>GENO, LHON<span class="sc">$</span>PHENO)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    
     CASE CONTROL
  CC    6      10
  CT    8      66
  TT   75     163</code></pre>
</div>
</div>
<ul>
<li>Functions like <code>as.numeric()</code> and <code>factor()</code> will be useful to convert between numeric and categorical variables.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>LHON<span class="sc">$</span>GENO[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co"># see the first 5 entries</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "TT" "CT" "TT" "CT" "TT"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>(<span class="fu">factor</span>(LHON<span class="sc">$</span>GENO, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"CC"</span>, <span class="st">"CT"</span>, <span class="st">"TT"</span>)))[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co"># convert to numeric specifying the order of the labels</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3 2 3 2 3</code></pre>
</div>
</div>
<ul>
<li>Note: For any R function you don’t know the input syntax, you can get that information using <code>?&lt;function_name&gt;</code>, e.g.&nbsp;<code>?table</code></li>
</ul>
</section>
<section id="exercises" class="level3">
<h3 class="anchored" data-anchor-id="exercises">Exercises</h3>
<p>Here are some things to look at:</p>
<ol type="1">
<li>Examine the variables in the dataset
<ul>
<li>How many observations? (use <code>str</code> function)</li>
<li>How many cases/controls? (use <code>table</code> function)</li>
<li>What are the genotypes present in the variable <code>GENO</code>? (use <code>table</code> function)
<ul>
<li>To visualize the counts, you can use <code>barplot(table(LHON$GENO))</code></li>
</ul></li>
<li>What is the distribution of the genotypes across cases/controls? (use <code>table</code> function)</li>
</ul></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(LHON<span class="sc">$</span>GENO))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QG3_Association_Testing_practical_Key_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the distribution of the genotypes across cases/controls</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(LHON<span class="sc">$</span>PHENO, LHON<span class="sc">$</span>GENO), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>,<span class="st">"red"</span>))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"CASE"</span>, <span class="st">"CONTROL"</span>), <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"blue"</span>,<span class="st">"red"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QG3_Association_Testing_practical_Key_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute allele frequency for allele 'T'</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>(<span class="dv">1</span> <span class="sc">*</span> <span class="fu">sum</span>(LHON<span class="sc">$</span>GENO <span class="sc">==</span> <span class="st">"CT"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">sum</span>(LHON<span class="sc">$</span>GENO <span class="sc">==</span> <span class="st">"TT"</span>)) <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> <span class="fu">nrow</span>(LHON))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8384146</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Perform a logistic regression analysis for this data with <code>CC</code> as the reference genotype using the <code>glm()</code> function.</li>
</ol>
<ul>
<li>First convert the <code>GENO</code> variable to a factor</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>GENO_factor <span class="ot">&lt;-</span> <span class="fu">factor</span>(LHON<span class="sc">$</span>GENO, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"CC"</span>, <span class="st">"CT"</span>, <span class="st">"TT"</span>)) <span class="co"># convert to numeric specifying the order of the labels</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Convert the phenotype to a 0/1 variable</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>pheno_binary <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">*</span> (LHON<span class="sc">$</span>PHENO <span class="sc">==</span> <span class="st">"CASE"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Check that the entries in <code>pheno_binary</code> with 1 correspond to <code>PHENO='CASE'</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pheno_binary, LHON<span class="sc">$</span>PHENO)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            
pheno_binary CASE CONTROL
           0    0     239
           1   89       0</code></pre>
</div>
</div>
<ul>
<li>Run logistic regression using the <code>glm</code> function</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>logistic_model_LHON <span class="ot">&lt;-</span> <span class="fu">glm</span>(pheno_binary <span class="sc">~</span> GENO_factor, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You can get information about the model fit and parameter estimates (i.e.&nbsp;coefficients):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic_model_LHON)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = pheno_binary ~ GENO_factor, family = binomial(link = "logit"))

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)    -0.5108     0.5164  -0.989   0.3226  
GENO_factorCT  -1.5994     0.6378  -2.508   0.0122 *
GENO_factorTT  -0.2654     0.5349  -0.496   0.6197  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 383.49  on 327  degrees of freedom
Residual deviance: 368.48  on 325  degrees of freedom
AIC: 374.48

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Obtain odds ratios and confidence intervals (CI) for the <code>CT</code> and <code>TT</code> genotypes relative to the <code>CC</code> reference genotype.
<ul>
<li>Use the lecture notes to obtain odds ratios &amp; CI from estimates and standard errors.</li>
<li><strong>Interpret the results</strong>: An odds ratio of 0.5 means what biologically? What about an OR of 2.0?</li>
</ul></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Odds ratios for CT</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.5994</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2020177</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Odds ratios for TT</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.2654</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7668991</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Other way for all genotypes at once</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(logistic_model_LHON))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) GENO_factorCT GENO_factorTT 
    0.6000000     0.2020202     0.7668712 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CI for CT</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>( <span class="sc">-</span><span class="fl">1.5994</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">*</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="fl">0.6378</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05787394 0.70517308</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CI for TT</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>( <span class="sc">-</span><span class="fl">0.2654</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">*</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="fl">0.5349</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2687956 2.1880353</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using R function `confint.default()`</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint.default</span>(logistic_model_LHON, <span class="at">level =</span> <span class="fl">0.95</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %   97.5 %
(Intercept)   0.21806837 1.650858
GENO_factorCT 0.05787424 0.705187
GENO_factorTT 0.26878265 2.187981</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Is there evidence of differences in odds of being a case for the <code>CT</code> and <code>TT</code> genotypes (compared to <code>CC</code>)?
<ul>
<li>Look at the p-values. What threshold would you use for significance?</li>
<li><strong>Important</strong>: This is a candidate gene study (1 variant tested). How would your significance threshold differ in a GWAS testing 1 million variants?</li>
</ul></li>
</ol>
<p><strong>Answer</strong>: Check the p-values. The CT genotype shows significant difference (p=0.012), but TT does not (p=0.62). For a candidate gene study, p &lt; 0.05 is reasonable. In a GWAS with 1M tests, we’d need p &lt; 5×10⁻⁸ (Bonferroni correction).</p>
<section id="extra" class="level4">
<h4 class="anchored" data-anchor-id="extra"><em>Extra</em></h4>
<ol start="5" type="1">
<li>Perform the logistic regression analysis with an additive genotype coding (e.g.&nbsp;counting the number of ‘T’ alleles).
<ul>
<li>Hint: To convert to numerical, create a new variable with values 0/1/2 based on the genotypes (you can then use <code>table()</code> function to make sure the new variable was defined correctly).</li>
</ul></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create additive coding variable</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>GENO_additive_T <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (LHON<span class="sc">$</span>GENO <span class="sc">==</span> <span class="st">"CT"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (LHON<span class="sc">$</span>GENO <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># check it is correct by comparing with the original variable</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(GENO_additive_T, LHON<span class="sc">$</span>GENO)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
GENO_additive_T  CC  CT  TT
              0  16   0   0
              1   0  74   0
              2   0   0 238</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the logistic model</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>logistic_model_additive_LHON <span class="ot">&lt;-</span> <span class="fu">glm</span>(pheno_binary <span class="sc">~</span> GENO_additive_T, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic_model_additive_LHON)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = pheno_binary ~ GENO_additive_T, family = binomial(link = "logit"))

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      -1.8077     0.4554  -3.970  7.2e-05 ***
GENO_additive_T   0.4787     0.2505   1.911   0.0559 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 383.49  on 327  degrees of freedom
Residual deviance: 379.47  on 326  degrees of freedom
AIC: 383.47

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<ol start="6" type="1">
<li>Obtain odds ratios and confidence intervals. Is there evidence of an association? How does it compare with the 2-parameter model?
<ul>
<li><strong>Think about</strong>: What assumption does the additive model make? When would this be appropriate vs the 2-parameter model?</li>
</ul></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(logistic_model_additive_LHON))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept) GENO_additive_T 
      0.1640322       1.6140439 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint.default</span>(logistic_model_additive_LHON, <span class="at">level =</span> <span class="fl">0.95</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     2.5 %    97.5 %
(Intercept)     0.06718883 0.4004616
GENO_additive_T 0.98792490 2.6369796</code></pre>
</div>
</div>
<p><strong>Comparison</strong>: The additive model gives OR = 1.61 per T allele (p=0.056). The 2-parameter model showed CT was strongly protective (OR=0.20, p=0.012) but TT was not (OR=0.77, p=0.62), suggesting the effect may not be truly additive.</p>
</section>
</section>
<section id="multiple-testing-considerations" class="level3">
<h3 class="anchored" data-anchor-id="multiple-testing-considerations">Multiple Testing Considerations</h3>
<p>In a real GWAS, we test hundreds of thousands to millions of variants. If we used p &lt; 0.05 for each test: - Testing 1,000,000 SNPs with no true effects - We’d expect 50,000 false positives (5% × 1,000,000)!</p>
<p><strong>Common corrections</strong>: - <strong>Bonferroni</strong>: p &lt; 0.05 / number_of_tests (e.g., p &lt; 5×10⁻⁸ for GWAS) - <strong>FDR (False Discovery Rate)</strong>: Controls proportion of false positives among discoveries</p>
<p><strong>For discussion</strong>: In our LHON analysis above, we tested 1 SNP with p=0.012. If this were part of a GWAS testing 1 million SNPs, this would NOT be considered significant (0.012 &gt; 5×10⁻⁸)!</p>
</section>
</section>
<section id="association-testing-with-quantitative-traits" class="level2">
<h2 class="anchored" data-anchor-id="association-testing-with-quantitative-traits">Association Testing with Quantitative Traits</h2>
<section id="introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="introduction-1">Introduction</h3>
<p>We will be using the <a href="https://raw.githubusercontent.com/joellembatchou/SISG2026_Association_Mapping/master/data/bpdata.csv">Blood Pressure dataset</a> for this portion of the exercises. This dataset contains diastolic and systolic blood pressure measurements for 1000 individuals, and genotype data at 11 SNPs in a candidate gene for blood pressure. Covariates such as gender (sex) and body mass index (bmi) are included as well.</p>
<p><strong>What we’re testing</strong>: Do individuals with different genotypes have different mean blood pressure values? We use linear regression because our outcome is continuous (quantitative trait).</p>
<p>Let’s first load the file into R. We need to define the path to the file (if you have it downloaded on your machine, change the path to the file location).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>BP_FILE <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/joellembatchou/SISG2026_Association_Mapping/master/data/bpdata.csv"</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Use the following command to read it into R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>BP <span class="ot">&lt;-</span> <span class="fu">fread</span>(BP_FILE, <span class="at">header=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Get a snippet of the data:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(BP, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   V1    sex sbp dbp snp1 snp2 snp3 snp4 snp5 snp6 snp7 snp8 snp9 snp10 snp11
1:  1 FEMALE 171  89   CC   TT   TT   TT   CC   GG   AA   TT   TT    CC    TT
2:  2   MALE 160  99   TT   TT   CC &lt;NA&gt;   CC   AG   AT   CC   CT    CC    CT
   bmi
1:  25
2:  35</code></pre>
</div>
</div>
</section>
<section id="exercises-1" class="level3">
<h3 class="anchored" data-anchor-id="exercises-1">Exercises</h3>
<p>Here are some things to try:</p>
<ol type="1">
<li>Perform a linear regression of systolic blood pressure (<code>sbp</code>) on <code>SNP3</code> using the <code>lm()</code> function.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>linear_model_BP <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> snp3, <span class="at">data =</span> BP)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You can get information about the model fit and parameter estimates (i.e.&nbsp;coefficients):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model_BP)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sbp ~ snp3, data = BP)

Residuals:
    Min      1Q  Median      3Q     Max 
-55.931 -12.428  -0.931  10.572  60.572 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 140.4283     0.7361 190.773   &lt;2e-16 ***
snp3TC        2.5026     1.2840   1.949   0.0516 .  
snp3TT        5.2859     3.1868   1.659   0.0975 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.34 on 957 degrees of freedom
  (40 observations deleted due to missingness)
Multiple R-squared:  0.006019,  Adjusted R-squared:  0.003942 
F-statistic: 2.898 on 2 and 957 DF,  p-value: 0.05563</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Is there any evidence of an effect of the SNP on systolic blood pressure?
<ul>
<li>Check the p-values in the summary output.</li>
<li><strong>Interpret the results</strong>: What do the SNP coefficients mean? How much higher/lower is blood pressure for individuals with different genotypes?</li>
</ul></li>
</ol>
<p>Check the p-values. Neither TC (p=0.052) nor TT (p=0.098) show significant associations at the 0.05 level. TC individuals have ~2.5 mmHg higher SBP than CC; TT individuals have ~5.3 mmHg higher SBP than CC (though these are not statistically significant).</p>
<ol start="3" type="1">
<li>Provide a plot illustrating the relationship between sbp and the three genotypes at SNP3.</li>
</ol>
<ul>
<li>How does it compare with the linear model fitted in question (1)?</li>
<li><strong>Think about</strong>: Does the boxplot suggest an additive effect (evenly spaced means) or something else?</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show the mean in the boxplots (by default, only the median is shown)</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(BP, {</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Draw the boxplots</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">boxplot</span>(sbp <span class="sc">~</span> snp3)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate means</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  means <span class="ot">&lt;-</span> <span class="fu">tapply</span>(sbp, snp3, mean)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add means to the boxplots</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(means), <span class="at">y =</span> means, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">pch =</span> <span class="dv">18</span>)</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QG3_Association_Testing_practical_Key_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The boxplot shows mean SBP increasing from CC → TC → TT, suggesting an approximately additive effect.</p>
<ol start="4" type="1">
<li><p>By default, the 2-parameter model is used since the SNP is stored in the data as categorical. Contrast the parameter estimates, p-values and confidence intervals obtained between this model and using:</p>
<ul>
<li>additive (linear) model (counting the T allele)</li>
<li>dominant model</li>
<li>recessive model</li>
</ul></li>
</ol>
<p><em>Hint</em>: for each case, generate the appropriate allele coding variable and pass it to the <code>lm()</code> function. For example with additive coding:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>SNP3_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp3 <span class="sc">==</span> <span class="st">"TC"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp3 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>linear_model_BP_additive <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> SNP3_additive, <span class="at">data =</span> BP)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model_BP_additive)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sbp ~ SNP3_additive, data = BP)

Residuals:
    Min      1Q  Median      3Q     Max 
-55.974 -12.418  -0.974  10.582  60.582 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   140.4179     0.7219 194.506   &lt;2e-16 ***
SNP3_additive   2.5556     1.0615   2.407   0.0163 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.33 on 958 degrees of freedom
  (40 observations deleted due to missingness)
Multiple R-squared:  0.006014,  Adjusted R-squared:  0.004976 
F-statistic: 5.796 on 1 and 958 DF,  p-value: 0.01625</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>SNP3_dominant <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp3 <span class="sc">==</span> <span class="st">"TC"</span>) <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp3 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>linear_model_BP_dominant <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> SNP3_dominant, <span class="at">data =</span> BP)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model_BP_dominant)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sbp ~ SNP3_dominant, data = BP)

Residuals:
    Min      1Q  Median      3Q     Max 
-56.218 -12.428  -0.823  10.572  60.572 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    140.428      0.736 190.801   &lt;2e-16 ***
SNP3_dominant    2.790      1.238   2.253   0.0245 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.34 on 958 degrees of freedom
  (40 observations deleted due to missingness)
Multiple R-squared:  0.005269,  Adjusted R-squared:  0.00423 
F-statistic: 5.074 on 1 and 958 DF,  p-value: 0.02451</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>SNP3_recessive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">0</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp3 <span class="sc">==</span> <span class="st">"TC"</span>) <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp3 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>linear_model_BP_recessive <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> SNP3_recessive, <span class="at">data =</span> BP)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model_BP_recessive)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sbp ~ SNP3_recessive, data = BP)

Residuals:
    Min      1Q  Median      3Q     Max 
-54.251 -12.501  -1.251  10.749  59.749 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     141.251      0.604 233.854   &lt;2e-16 ***
SNP3_recessive    4.463      3.163   1.411    0.159    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.37 on 958 degrees of freedom
  (40 observations deleted due to missingness)
Multiple R-squared:  0.002074,  Adjusted R-squared:  0.001032 
F-statistic: 1.991 on 1 and 958 DF,  p-value: 0.1586</code></pre>
</div>
</div>
<p><strong>Comparison</strong>: - <strong>Additive</strong>: Each T allele associated with +2.6 mmHg (p=0.016) - simplest, most powerful if effect is truly additive - <strong>Dominant</strong>: TC or TT associated with +2.8 mmHg vs CC (p=0.025) - assumes one copy is enough for full effect - <strong>Recessive</strong>: TT associated with +4.5 mmHg vs CC/TC (p=0.159) - assumes need two copies for effect (not significant)</p>
<p>For question 5 and 6 below, R also has a ‘formula’ syntax, frequently used when specifying regression models with many predictors. To regress an outcome <code>y</code> on several covariates, the syntax is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> covariate1 <span class="sc">+</span> covariate2 <span class="sc">+</span> covariate3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="5" type="1">
<li>Now redo the linear regression analysis of <code>sbp</code> from question 4 for the <strong>additive model</strong>, but this time adjust for <code>sex</code> and <code>bmi</code>. Do the results change?
<ul>
<li><strong>Important concept</strong>: Why do we adjust for covariates? What confounding could <code>bmi</code> or <code>sex</code> introduce?</li>
<li>Compare the SNP effect estimate and p-value before and after covariate adjustment.</li>
</ul></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>linear_model_BP_cov_adj <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> sex <span class="sc">+</span> bmi <span class="sc">+</span> SNP3_additive, <span class="at">data =</span> BP)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model_BP_cov_adj)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sbp ~ sex + bmi + SNP3_additive, data = BP)

Residuals:
   Min     1Q Median     3Q    Max 
-58.83 -12.81  -0.82  11.58  57.80 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   145.85380    3.00271  48.574  &lt; 2e-16 ***
sexMALE        -4.77580    1.17642  -4.060 5.32e-05 ***
bmi            -0.09837    0.09481  -1.038   0.2997    
SNP3_additive   2.63566    1.05434   2.500   0.0126 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.19 on 955 degrees of freedom
  (41 observations deleted due to missingness)
Multiple R-squared:  0.02402,   Adjusted R-squared:  0.02096 
F-statistic: 7.836 on 3 and 955 DF,  p-value: 3.608e-05</code></pre>
</div>
</div>
<p>The SNP effect remains similar (+2.64 mmHg per T allele, p=0.013). Sex is a significant predictor (males have ~4.8 mmHg lower SBP), while BMI is not significant. Adjusting for these covariates does not substantially change the genetic effect.</p>
<section id="extra-1" class="level4">
<h4 class="anchored" data-anchor-id="extra-1"><em>Extra</em></h4>
<ol start="6" type="1">
<li>What proportion of the variance of <code>sbp</code> is explained by all 11 SNPs combined using categorical coding?</li>
</ol>
<ul>
<li>Use the <code>summary()</code> function to see the model results (the proportion of variance is the “Multiple R-squared” quantity)</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>linear_model_BP_all_snps <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> snp1<span class="sc">+</span>snp2<span class="sc">+</span>snp3<span class="sc">+</span>snp4<span class="sc">+</span>snp5<span class="sc">+</span>snp6<span class="sc">+</span>snp7<span class="sc">+</span>snp8<span class="sc">+</span>snp9<span class="sc">+</span>snp10<span class="sc">+</span>snp11, <span class="at">data =</span> BP)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model_BP_all_snps)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sbp ~ snp1 + snp2 + snp3 + snp4 + snp5 + snp6 + 
    snp7 + snp8 + snp9 + snp10 + snp11, data = BP)

Residuals:
    Min      1Q  Median      3Q     Max 
-50.722 -11.967  -0.703  11.021  61.704 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 133.1726    12.4033  10.737   &lt;2e-16 ***
snp1CT       -1.7048     4.5991  -0.371    0.711    
snp1TT        1.9319     8.2839   0.233    0.816    
snp2AT        0.7347     5.5923   0.131    0.896    
snp2TT       -0.5118     6.9317  -0.074    0.941    
snp3TC        4.7672     5.0211   0.949    0.343    
snp3TT        6.6913     9.7904   0.683    0.495    
snp4CT       -0.4778     3.5501  -0.135    0.893    
snp4TT        2.3431     6.4874   0.361    0.718    
snp5CT        1.1896     3.0462   0.391    0.696    
snp5TT       -2.2787     7.5490  -0.302    0.763    
snp6AG       -3.0266     2.0697  -1.462    0.144    
snp6GG        2.1230     4.6650   0.455    0.649    
snp7AT       -3.0873     3.9148  -0.789    0.431    
snp7TT       -2.6319     4.3146  -0.610    0.542    
snp8CT       -1.5509     3.6318  -0.427    0.669    
snp8TT       -2.5507     7.3228  -0.348    0.728    
snp9CT        6.0693     7.6170   0.797    0.426    
snp9TT        4.7385     7.4517   0.636    0.525    
snp10CT       1.4330     1.6466   0.870    0.384    
snp10TT       1.9810     2.0699   0.957    0.339    
snp11CT       4.8005     6.5175   0.737    0.462    
snp11TT       4.0226     9.2775   0.434    0.665    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.2 on 707 degrees of freedom
  (270 observations deleted due to missingness)
Multiple R-squared:  0.02633,   Adjusted R-squared:  -0.003965 
F-statistic: 0.8691 on 22 and 707 DF,  p-value: 0.6372</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model_BP_all_snps)<span class="sc">$</span>r.sq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02633265</code></pre>
</div>
</div>
<ul>
<li>How would it differ if an additive coding is used for the 11 SNPs?
<ul>
<li>use <code>unique()</code> to check the genotypes for each SNP, e.g.&nbsp;<code>unique(BP$snp1)</code></li>
<li>count the T allele (or A allele if applicable)</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(BP<span class="sc">$</span>snp1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CC" "TT" "CT" NA  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>SNP1_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp1 <span class="sc">==</span> <span class="st">"CT"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp1 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(BP<span class="sc">$</span>snp2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "TT" "AT" "AA" NA  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>SNP2_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp2 <span class="sc">==</span> <span class="st">"AT"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp2 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(BP<span class="sc">$</span>snp3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "TT" "CC" "TC" NA  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>SNP3_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp3 <span class="sc">==</span> <span class="st">"TC"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp3 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(BP<span class="sc">$</span>snp4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "TT" NA   "CT" "CC"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>SNP4_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp4 <span class="sc">==</span> <span class="st">"CT"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp4 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(BP<span class="sc">$</span>snp5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CC" NA   "CT" "TT"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>SNP5_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp5 <span class="sc">==</span> <span class="st">"CT"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp5 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(BP<span class="sc">$</span>snp6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "GG" "AG" "AA" NA  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>SNP6_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp6 <span class="sc">==</span> <span class="st">"AG"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp6 <span class="sc">==</span> <span class="st">"AA"</span>)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(BP<span class="sc">$</span>snp7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "AA" "AT" "TT" NA  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>SNP7_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp7 <span class="sc">==</span> <span class="st">"AT"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp7 <span class="sc">==</span> <span class="st">"AA"</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(BP<span class="sc">$</span>snp8)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "TT" "CC" "CT" NA  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>SNP8_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp8 <span class="sc">==</span> <span class="st">"CT"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp8 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(BP<span class="sc">$</span>snp9)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "TT" "CT" NA   "CC"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>SNP9_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp9 <span class="sc">==</span> <span class="st">"CT"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp9 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(BP<span class="sc">$</span>snp10)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CC" "CT" "TT" NA  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>SNP10_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp10 <span class="sc">==</span> <span class="st">"CT"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp10 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(BP<span class="sc">$</span>snp11)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "TT" "CT" "CC" NA  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>SNP11_additive <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp11 <span class="sc">==</span> <span class="st">"CT"</span>) <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (BP<span class="sc">$</span>snp11 <span class="sc">==</span> <span class="st">"TT"</span>)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>linear_model_BP_all_snps_additive <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> SNP1_additive<span class="sc">+</span>SNP2_additive<span class="sc">+</span>SNP3_additive<span class="sc">+</span>SNP4_additive<span class="sc">+</span>SNP5_additive<span class="sc">+</span>SNP6_additive<span class="sc">+</span>SNP7_additive<span class="sc">+</span>SNP8_additive<span class="sc">+</span>SNP9_additive<span class="sc">+</span>SNP10_additive<span class="sc">+</span>SNP11_additive, <span class="at">data =</span> BP)</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model_BP_all_snps_additive)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sbp ~ SNP1_additive + SNP2_additive + SNP3_additive + 
    SNP4_additive + SNP5_additive + SNP6_additive + SNP7_additive + 
    SNP8_additive + SNP9_additive + SNP10_additive + SNP11_additive, 
    data = BP)

Residuals:
    Min      1Q  Median      3Q     Max 
-53.638 -12.849  -0.522  11.032  61.683 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    134.43839    9.42384  14.266   &lt;2e-16 ***
SNP1_additive    1.88456    4.03838   0.467    0.641    
SNP2_additive   -1.95639    2.96674  -0.659    0.510    
SNP3_additive    4.60730    4.65652   0.989    0.323    
SNP4_additive    0.05946    3.11138   0.019    0.985    
SNP5_additive   -0.26494    2.58719  -0.102    0.918    
SNP6_additive    1.17284    1.80185   0.651    0.515    
SNP7_additive    0.28939    1.78362   0.162    0.871    
SNP8_additive    0.70702    2.78030   0.254    0.799    
SNP9_additive    2.17197    2.54774   0.853    0.394    
SNP10_additive   0.60685    1.01229   0.599    0.549    
SNP11_additive  -0.39009    4.15347  -0.094    0.925    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.17 on 718 degrees of freedom
  (270 observations deleted due to missingness)
Multiple R-squared:  0.01418,   Adjusted R-squared:  -0.0009268 
F-statistic: 0.9386 on 11 and 718 DF,  p-value: 0.5022</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model_BP_all_snps_additive)<span class="sc">$</span>r.sq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01417639</code></pre>
</div>
</div>
<p>Categorical coding: R² ≈ 0.026 (2.6% variance explained) Additive coding: R² ≈ 0.014 (1.4% variance explained)</p>
<p>The categorical model explains more variance than the additive model, suggesting that the SNP effects may not be perfectly additive. These 11 SNPs explain only ~1-3% of SBP variation, meaning ~97-99% is due to other factors (environment, other genes, measurement error).</p>
<hr>
</section>
</section>
</section>
<section id="key-takeaways-from-this-practical" class="level2">
<h2 class="anchored" data-anchor-id="key-takeaways-from-this-practical">Key Takeaways from This Practical</h2>
<p><strong>Concepts you should understand:</strong></p>
<ol type="1">
<li><strong>Regression framework</strong>: Both logistic and linear regression test for association while accounting for covariates</li>
<li><strong>Odds ratios vs effect sizes</strong>: OR &lt; 1 means protective; OR &gt; 1 means risk-increasing; effect size is change in trait mean per allele</li>
<li><strong>Genotype encoding</strong>: Additive (0/1/2) assumes linear relationship; 2-parameter model allows any pattern</li>
<li><strong>Multiple testing</strong>: Must correct for number of tests to avoid false positives (p &lt; 5×10⁻⁸ for GWAS)</li>
<li><strong>Interpretation matters</strong>: Statistical significance depends on sample size, but biological relevance depends on effect size</li>
</ol>
<p><strong>You are NOT expected to:</strong></p>
<ul>
<li>Memorize R syntax (you can look it up!)</li>
<li>Become an R expert</li>
<li>Finish every question</li>
</ul>
<p><strong>Next session:</strong> We’ll see why population structure (ancestry) can cause spurious associations and how to detect it.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>